#!/bin/bash
#SBATCH --job-name=f_gzunzip
#SBATCH --ntasks=1
#SBATCH --mem=32gb
#SBATCH --time=4:20:00
#SBATCH --partition=notchpeak-guest
#SBATCH --account=owner-guest
#SBATCH --mail-type=ALL
#SBATCH --mail-user=garrett.otrimski@hci.utah.edu



echo "start of job"

cd /uufs/chpc.utah.edu/common/home/holmen-group1/otrimskig/23908R/Fastq

for i in *.gz;
do gunzip $i;
done







echo "end of job :)"
