#!/bin/bash
#SBATCH --job-name=bam_merg
#SBATCH --ntasks=40
#SBATCH --mem=42gb
#SBATCH --time=5:00:00
#SBATCH --partition=lonepeak-guest
#SBATCH --account=owner-guest
#SBATCH --mail-type=ALL
#SBATCH --mail-user=garrett.otrimski@hci.utah.edu
#SBATCH --output=/uufs/chpc.utah.edu/common/home/holmen-group1/otrimskig/outs/slurm-%j.out

#create start timestamps.
start_time=$(date +%s)
echo "$(date "+%Y-%m-%d %H:%M:%S") : started job "

#load modules
module load samtools


#set working directory path
cd /uufs/chpc.utah.edu/common/home/holmen-group1/otrimskig/exp_data/


#define directory path variables
directory1="./23908R1/bams/"
directory2="./23908R2/bams/"
output_directory="./23908R_merged/"

for bam1 in "${directory1}"*.bam; do

sample_number=$(basename "$bam1" | grep -o '23908X[0-9]\+')

bam2=$(find "$directory2" -name "${sample_number}*.bam")

output_file="${output_directory}${sample_number}_merged.bam"



if [ -n "$bam2" ]; then


echo "$(date "+%Y-%m-%d %H:%M:%S") : merging $bam1 and $bam2"
echo "$(date "+%Y-%m-%d %H:%M:%S") : writing to $output_file"


samtools merge -@ 40 "$bam1" "$bam2" -o "$output_file"

echo -e "\n"
echo "$(date "+%Y-%m-%d %H:%M:%S") : indexing $output_file"


samtools index "$output_file"


echo -e "\n\n\n\n\n"


echo "$(date "+%Y-%m-%d %H:%M:%S") : done"

else
echo "No match found for $bam1 in $directory2"
echo -e "\n\n\n\n\n"
fi


done



echo "$(date "+%Y-%m-%d %H:%M:%S") : ended job "

end_time=$(date +%s)
runtime=$((end_time - start_time))
hours=$((runtime / 3600))
minutes=$(( (runtime % 3600) / 60 ))
seconds=$((runtime % 60))

echo "Runtime: $hours:$minutes:$seconds"
