#!/bin/bash
#SBATCH --job-name=slupa
#SBATCH --array=1-10
#SBATCH --ntasks=10
#SBATCH --mem=10gb
#SBATCH --time=0:01:00
#SBATCH --partition=lonepeak-guest
#SBATCH --account=owner-guest
#SBATCH --mail-type=ALL
#SBATCH --mail-user=garrett.otrimski@hci.utah.edu
#SBATCH --output=/uufs/chpc.utah.edu/common/home/holmen-group1/otrimskig/outs/slurm-%j_%a.out

#create start timestamps.
start_time=$(date +%s)
echo "$(date "+%Y-%m-%d %H:%M:%S") : started job "

#load modules

#set working directory path
cd /uufs/chpc.utah.edu/common/home/holmen-group1/otrimskig/exp_data/

#specify config file
config=/uufs/chpc.utah.edu/common/home/holmen-group1/otrimskig/scr/configs/config1.txt

# echo $SLURM_ARRAY_TASK_ID
echo "task ID: $SLURM_ARRAY_TASK_ID" 

# Extract the sample name for the current $SLURM_ARRAY_TASK_ID
sample=$(awk -v ArrayTaskID=$SLURM_ARRAY_TASK_ID '$1==ArrayTaskID {print $2}' $config)


echo "sample: $sample"


echo "$(date "+%Y-%m-%d %H:%M:%S") : ended job "

end_time=$(date +%s)
runtime=$((end_time - start_time))
hours=$((runtime / 3600))
minutes=$(( (runtime % 3600) / 60 ))
seconds=$((runtime % 60))

echo "Runtime: $hours:$minutes:$seconds"
